services:
  db:
    image : postgres:latest
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/

volumes:
  db_data: